# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lint-project

jobs:
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
          
      - name: Install libcurl4
        run:  sudo apt-get install -y libcurl4-openssl-dev
    
      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}    
      
      - uses: ./

      - name: Install shiny
        run: install.packages("shiny")
        shell: Rscript {0}

      - name: Install shinydashboard
        run: install.packages("shinydashboard")
        shell: Rscript {0}
        
      - name: Install DT
        run: install.packages("DT")
        shell: Rscript {0}

      - name: Install tidyverse
        run: install.packages("tidyverse")
        shell: Rscript {0}

      - name: Install tidyquant
        run: install.packages("tidyquant")
        shell: Rscript {0}

      - name: Install quantmod
        run: install.packages("quantmod")
        shell: Rscript {0}

      - name: Install crypto2
        run: install.packages("crypto2")
        shell: Rscript {0}

      - name: Install plotly"
        run: install.packages("plotly")
        shell: Rscript {0}

      - name: Install lintr
        run: devtools::install_github("jimhester/lintr")
        shell: Rscript {0}

      - name: Lint root directory
        run: lintr::lint_dir()
        shell: Rscript {0}
        
        
