on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: run-tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Install libcurl4
        run:  sudo apt-get install -y libcurl4-openssl-dev
      
      - name: Install dependencies
        run: |
          install.packages("devtools")
        shell: Rscript {0}
      
      - name: Run unit tests
        run: devtools::test(reporter = c('progress', 'fail'))
        shell: Rscript {0}