on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: run-tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libxml2 libxml2-dev
    
      - name: Install R dependencies
        run: | 
          install.packages("devtools")
          install.packages('renv')
          renv::activate()
          renv::restore()
        shell: Rscript {0} 
            
      - name: Run unit tests
        run: devtools::test(reporter = c('progress', 'fail'))
        shell: Rscript {0}